plugins:
  telegram_auth_enabled:
    default: false
  telegram_auth_bot_name:
    default: ''
    regex: ".+[Bb]ot"
  telegram_access_token:
    default: ''
    regex: "^[0-9]{10}:[a-zA-Z0-9_-]{35}$"
