plugins:
  telegram_auth_enabled:
    default: false
    client: true
  telegram_auth_bot_name:
    default: ''
    regex: "^[a-zA-Z][a-zA-Z0-9_]{3,}[Bb]ot$"
    min: 5
    max: 64
  telegram_auth_bot_token:
    default: ''
    regex: "^[0-9]{8,10}:[a-zA-Z0-9_-]{35}$"
    secret: true
  telegram_auth_debug:
    default: false
    client: false
    hidden: true
